import { MigrationInterface, QueryRunner } from 'typeorm'

export class Products1636910518366 implements MigrationInterface {
   public async up(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`insert into product (id, name, description, "unitPrice", "unitWeight") values (1, 'F-Series Super Duty', 'Vision-oriented optimizing task-force', 70.73, 3.05);
insert into product (id, name, description, "unitPrice", "unitWeight") values (2, '9000', 'Business-focused didactic productivity', 14.72, 8.92);
insert into product (id, name, description, "unitPrice", "unitWeight") values (3, 'Tribute', 'Virtual context-sensitive product', 76.26, 85.6);
insert into product (id, name, description, "unitPrice", "unitWeight") values (4, 'Lancer', 'Pre-emptive multi-state instruction set', 33.65, 88.05);
insert into product (id, name, description, "unitPrice", "unitWeight") values (5, 'Sienna', 'Adaptive incremental standardization', 11.93, 12.52);
insert into product (id, name, description, "unitPrice", "unitWeight") values (6, 'Gran Sport', 'Cross-group bi-directional firmware', 98.14, 44.75);
insert into product (id, name, description, "unitPrice", "unitWeight") values (7, 'Cooper', 'Organized national alliance', 78.96, 37.56);
insert into product (id, name, description, "unitPrice", "unitWeight") values (8, 'Grand Prix', 'Upgradable encompassing architecture', 77.5, 4.71);
insert into product (id, name, description, "unitPrice", "unitWeight") values (9, 'E-Class', 'Reverse-engineered impactful definition', 96.92, 25.46);
insert into product (id, name, description, "unitPrice", "unitWeight") values (10, 'RX', 'Reactive zero tolerance strategy', 4.08, 91.26);
insert into product (id, name, description, "unitPrice", "unitWeight") values (11, 'Previa', 'Synchronised grid-enabled system engine', 82.2, 80.28);
insert into product (id, name, description, "unitPrice", "unitWeight") values (12, 'Cirrus', 'Front-line asynchronous customer loyalty', 9.88, 81.84);
insert into product (id, name, description, "unitPrice", "unitWeight") values (13, 'Skylark', 'Horizontal mobile definition', 82.49, 14.45);
insert into product (id, name, description, "unitPrice", "unitWeight") values (14, 'Liberty', 'Re-engineered 6th generation intranet', 85.37, 18.17);
insert into product (id, name, description, "unitPrice", "unitWeight") values (15, '1000', 'Expanded composite projection', 54.16, 41.45);
insert into product (id, name, description, "unitPrice", "unitWeight") values (16, 'Sonoma Club Coupe', 'Cross-group regional projection', 16.4, 35.14);
insert into product (id, name, description, "unitPrice", "unitWeight") values (17, 'Neon', 'Advanced clear-thinking emulation', 82.19, 84.61);
insert into product (id, name, description, "unitPrice", "unitWeight") values (18, 'Escalade EXT', 'Reactive human-resource project', 38.09, 99.94);
insert into product (id, name, description, "unitPrice", "unitWeight") values (19, '80', 'Secured fault-tolerant framework', 12.84, 60.14);
insert into product (id, name, description, "unitPrice", "unitWeight") values (20, 'Accent', 'Up-sized bi-directional middleware', 34.24, 58.32);
insert into product (id, name, description, "unitPrice", "unitWeight") values (21, 'Jimmy', 'Focused methodical complexity', 68.1, 28.75);
insert into product (id, name, description, "unitPrice", "unitWeight") values (22, 'Vantage', 'Organic multi-state matrix', 17.65, 35.03);
insert into product (id, name, description, "unitPrice", "unitWeight") values (23, 'GX', 'Sharable contextually-based attitude', 17.73, 29.23);
insert into product (id, name, description, "unitPrice", "unitWeight") values (24, 'Hombre', 'Managed analyzing process improvement', 41.66, 7.3);
insert into product (id, name, description, "unitPrice", "unitWeight") values (25, 'Roadmaster', 'Reverse-engineered analyzing capacity', 68.76, 8.76);
insert into product (id, name, description, "unitPrice", "unitWeight") values (26, 'Sentra', 'Focused tangible focus group', 92.37, 86.26);
insert into product (id, name, description, "unitPrice", "unitWeight") values (27, 'Yukon XL 1500', 'Phased context-sensitive protocol', 64.74, 12.37);
insert into product (id, name, description, "unitPrice", "unitWeight") values (28, 'SLR McLaren', 'Cross-platform tangible focus group', 92.19, 66.75);
insert into product (id, name, description, "unitPrice", "unitWeight") values (29, 'tC', 'Programmable human-resource monitoring', 36.04, 50.12);
insert into product (id, name, description, "unitPrice", "unitWeight") values (30, 'Ram Wagon B250', 'Expanded national help-desk', 24.26, 13.68);
insert into product (id, name, description, "unitPrice", "unitWeight") values (31, 'Ram Wagon B350', 'Reactive intangible contingency', 16.0, 70.31);
insert into product (id, name, description, "unitPrice", "unitWeight") values (32, 'F150', 'Right-sized optimal installation', 56.13, 72.46);
insert into product (id, name, description, "unitPrice", "unitWeight") values (33, 'Neon', 'Integrated incremental groupware', 53.49, 45.09);
insert into product (id, name, description, "unitPrice", "unitWeight") values (34, 'Grand Prix', 'Exclusive uniform matrix', 66.21, 50.87);
insert into product (id, name, description, "unitPrice", "unitWeight") values (35, 'Avalanche 2500', 'De-engineered maximized hierarchy', 48.14, 74.01);
insert into product (id, name, description, "unitPrice", "unitWeight") values (36, 'Explorer', 'Public-key intermediate extranet', 48.95, 50.13);
insert into product (id, name, description, "unitPrice", "unitWeight") values (37, 'Tahoe', 'Multi-tiered fault-tolerant process improvement', 15.29, 55.8);
insert into product (id, name, description, "unitPrice", "unitWeight") values (38, 'Grand Marquis', 'Polarised directional adapter', 15.6, 33.81);
insert into product (id, name, description, "unitPrice", "unitWeight") values (39, 'Tahoe', 'Multi-lateral actuating alliance', 39.5, 85.66);
insert into product (id, name, description, "unitPrice", "unitWeight") values (40, 'Miata MX-5', 'Customer-focused systematic knowledge base', 11.5, 41.72);
insert into product (id, name, description, "unitPrice", "unitWeight") values (41, 'Suburban', 'Public-key bandwidth-monitored ability', 47.48, 66.07);
insert into product (id, name, description, "unitPrice", "unitWeight") values (42, 'Murano', 'Re-engineered neutral pricing structure', 63.75, 6.63);
insert into product (id, name, description, "unitPrice", "unitWeight") values (43, 'M-Class', 'Extended radical toolset', 42.62, 5.26);
insert into product (id, name, description, "unitPrice", "unitWeight") values (44, 'Routan', 'Cross-platform 24/7 policy', 22.87, 80.11);
insert into product (id, name, description, "unitPrice", "unitWeight") values (45, 'Yukon XL 2500', 'Upgradable next generation core', 24.52, 47.78);
insert into product (id, name, description, "unitPrice", "unitWeight") values (46, 'Tempo', 'Pre-emptive didactic strategy', 61.22, 58.95);
insert into product (id, name, description, "unitPrice", "unitWeight") values (47, 'Camaro', 'Fundamental web-enabled internet solution', 52.87, 96.53);
insert into product (id, name, description, "unitPrice", "unitWeight") values (48, 'Sephia', 'Extended static installation', 58.17, 61.12);
insert into product (id, name, description, "unitPrice", "unitWeight") values (49, 'Miata MX-5', 'Object-based responsive open system', 63.8, 71.12);
insert into product (id, name, description, "unitPrice", "unitWeight") values (50, 'Civic', 'Digitized interactive secured line', 84.99, 70.51);
insert into product (id, name, description, "unitPrice", "unitWeight") values (51, 'Bronco', 'Right-sized zero administration data-warehouse', 39.41, 43.29);
insert into product (id, name, description, "unitPrice", "unitWeight") values (52, '650', 'Switchable fresh-thinking firmware', 96.52, 55.04);
insert into product (id, name, description, "unitPrice", "unitWeight") values (53, 'Santa Fe', 'Fully-configurable bandwidth-monitored model', 99.45, 1.86);
insert into product (id, name, description, "unitPrice", "unitWeight") values (54, 'V70', 'Progressive discrete interface', 39.5, 33.7);
insert into product (id, name, description, "unitPrice", "unitWeight") values (55, 'Commander', 'Re-engineered coherent time-frame', 8.09, 82.56);
insert into product (id, name, description, "unitPrice", "unitWeight") values (56, 'Sentra', 'Integrated executive hierarchy', 75.14, 12.93);
insert into product (id, name, description, "unitPrice", "unitWeight") values (57, 'GTO', 'Managed incremental initiative', 33.44, 47.76);
insert into product (id, name, description, "unitPrice", "unitWeight") values (58, 'Skyhawk', 'Centralized maximized installation', 40.32, 36.37);
insert into product (id, name, description, "unitPrice", "unitWeight") values (59, 'Terraza', 'Managed secondary workforce', 81.31, 27.83);
insert into product (id, name, description, "unitPrice", "unitWeight") values (60, 'F150', 'Virtual tangible knowledge user', 49.15, 32.28);
insert into product (id, name, description, "unitPrice", "unitWeight") values (61, 'Pathfinder', 'Reduced logistical core', 32.52, 96.96);
insert into product (id, name, description, "unitPrice", "unitWeight") values (62, '300E', 'Public-key directional capability', 20.24, 77.99);
insert into product (id, name, description, "unitPrice", "unitWeight") values (63, 'S40', 'Face to face holistic functionalities', 11.65, 2.76);
insert into product (id, name, description, "unitPrice", "unitWeight") values (64, 'XL-7', 'Digitized mission-critical toolset', 59.34, 69.12);
insert into product (id, name, description, "unitPrice", "unitWeight") values (65, 'Tracer', 'De-engineered client-driven encoding', 79.23, 39.46);
insert into product (id, name, description, "unitPrice", "unitWeight") values (66, 'Sable', 'Vision-oriented intangible leverage', 21.62, 1.81);
insert into product (id, name, description, "unitPrice", "unitWeight") values (67, 'Grand Caravan', 'Function-based analyzing array', 86.51, 27.26);
insert into product (id, name, description, "unitPrice", "unitWeight") values (68, 'Ram 2500', 'Reactive empowering complexity', 87.84, 40.95);
insert into product (id, name, description, "unitPrice", "unitWeight") values (69, 'Monterey', 'Visionary zero defect installation', 88.37, 22.42);
insert into product (id, name, description, "unitPrice", "unitWeight") values (70, 'TT', 'Managed dynamic architecture', 98.91, 66.76);
insert into product (id, name, description, "unitPrice", "unitWeight") values (71, 'FJ Cruiser', 'Switchable clear-thinking application', 38.78, 36.72);
insert into product (id, name, description, "unitPrice", "unitWeight") values (72, 'GX', 'Quality-focused systemic open architecture', 60.94, 46.01);
insert into product (id, name, description, "unitPrice", "unitWeight") values (73, 'R-Class', 'Exclusive static functionalities', 58.18, 21.21);
insert into product (id, name, description, "unitPrice", "unitWeight") values (74, 'Cherokee', 'Digitized foreground circuit', 34.78, 2.95);
insert into product (id, name, description, "unitPrice", "unitWeight") values (75, 'Stratus', 'Universal hybrid monitoring', 62.59, 45.4);
insert into product (id, name, description, "unitPrice", "unitWeight") values (76, 'H3', 'Stand-alone web-enabled focus group', 23.98, 90.0);
insert into product (id, name, description, "unitPrice", "unitWeight") values (77, 'Camaro', 'Innovative client-server time-frame', 11.0, 54.96);
insert into product (id, name, description, "unitPrice", "unitWeight") values (78, 'TSX', 'Triple-buffered motivating implementation', 54.53, 2.18);
insert into product (id, name, description, "unitPrice", "unitWeight") values (79, 'Grand Prix', 'Optional upward-trending data-warehouse', 54.58, 79.5);
insert into product (id, name, description, "unitPrice", "unitWeight") values (80, 'SLR McLaren', 'Team-oriented even-keeled framework', 5.43, 82.18);
insert into product (id, name, description, "unitPrice", "unitWeight") values (81, 'rio', 'Sharable methodical toolset', 23.13, 96.58);
insert into product (id, name, description, "unitPrice", "unitWeight") values (82, 'Grand Prix', 'Exclusive exuding application', 29.27, 6.81);
insert into product (id, name, description, "unitPrice", "unitWeight") values (83, 'Yukon XL 1500', 'Automated object-oriented collaboration', 72.42, 43.03);
insert into product (id, name, description, "unitPrice", "unitWeight") values (84, 'G37', 'Multi-lateral scalable intranet', 4.26, 21.92);
insert into product (id, name, description, "unitPrice", "unitWeight") values (85, 'Vantage', 'Seamless mission-critical alliance', 94.21, 11.24);
insert into product (id, name, description, "unitPrice", "unitWeight") values (86, 'Biturbo', 'Configurable mission-critical attitude', 80.73, 42.28);
insert into product (id, name, description, "unitPrice", "unitWeight") values (87, 'Range Rover', 'Optimized 24/7 circuit', 64.73, 12.54);
insert into product (id, name, description, "unitPrice", "unitWeight") values (88, 'V50', 'Integrated client-server parallelism', 66.49, 52.67);
insert into product (id, name, description, "unitPrice", "unitWeight") values (89, 'Sidekick', 'Cross-group clear-thinking matrix', 26.94, 84.78);
insert into product (id, name, description, "unitPrice", "unitWeight") values (90, 'Azera', 'Public-key mission-critical toolset', 76.66, 48.02);
insert into product (id, name, description, "unitPrice", "unitWeight") values (91, 'F-Series', 'Switchable needs-based data-warehouse', 11.34, 39.38);
insert into product (id, name, description, "unitPrice", "unitWeight") values (92, 'Azure', 'Synergized non-volatile architecture', 82.22, 65.63);
insert into product (id, name, description, "unitPrice", "unitWeight") values (93, 'Z4 M Roadster', 'Configurable actuating contingency', 41.3, 64.26);
insert into product (id, name, description, "unitPrice", "unitWeight") values (94, '9-3', 'Persistent zero tolerance leverage', 2.64, 38.37);
insert into product (id, name, description, "unitPrice", "unitWeight") values (95, 'Protege', 'Switchable exuding hub', 37.24, 98.3);
insert into product (id, name, description, "unitPrice", "unitWeight") values (96, 'S4', 'Organic responsive hub', 18.03, 88.2);
insert into product (id, name, description, "unitPrice", "unitWeight") values (97, 'A6', 'Versatile human-resource analyzer', 45.04, 11.64);
insert into product (id, name, description, "unitPrice", "unitWeight") values (98, 'Accent', 'Diverse responsive data-warehouse', 43.56, 76.34);
insert into product (id, name, description, "unitPrice", "unitWeight") values (99, 'G8', 'Face to face user-facing intranet', 90.45, 64.65);
insert into product (id, name, description, "unitPrice", "unitWeight") values (100, 'Truck', 'Horizontal motivating installation', 52.24, 1.73);

        `)
   }

   public async down(queryRunner: QueryRunner): Promise<void> {}
}
