import { MigrationInterface, QueryRunner } from 'typeorm'

export class Orders1636919365010 implements MigrationInterface {
   public async up(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`insert into "order" (username, email, phone, "statusId") values ('Annabal', 'athing0@stumbleupon.com', '423-800-8883', '1');
insert into "order" (username, email, phone, "statusId") values ('Essy', 'evoules1@amazon.com', '908-195-4440', '1');
insert into "order" (username, email, phone, "statusId") values ('Charla', 'comohun2@nbcnews.com', '699-856-1919', '1');
insert into "order" (username, email, phone, "statusId") values ('Myrtle', 'mlotwich3@ocn.ne.jp', '703-291-5793', '1');
insert into "order" (username, email, phone, "statusId") values ('Lindsay', 'lmucklow4@hubpages.com', '229-627-4516', '1');
insert into "order" (username, email, phone, "statusId") values ('Lynnelle', 'lgilbody5@51.la', '279-766-7635', '1');
insert into "order" (username, email, phone, "statusId") values ('Kaylil', 'kcasel6@gnu.org', '492-957-9484', '1');
insert into "order" (username, email, phone, "statusId") values ('Adeline', 'arough7@columbia.edu', '493-360-9382', '1');
insert into "order" (username, email, phone, "statusId") values ('Trudey', 'tlimb8@cdc.gov', '771-254-0423', '1');
insert into "order" (username, email, phone, "statusId") values ('Essa', 'enormavill9@liveinternet.ru', '258-781-1091', '1');
insert into "order" (username, email, phone, "statusId") values ('Juli', 'jvakhrusheva@surveymonkey.com', '438-938-8474', '1');
insert into "order" (username, email, phone, "statusId") values ('Caressa', 'carmerb@fotki.com', '320-335-0582', '1');
insert into "order" (username, email, phone, "statusId") values ('Rosaleen', 'rriochc@jalbum.net', '290-662-4516', '1');
insert into "order" (username, email, phone, "statusId") values ('Cissiee', 'csutcliffed@blogtalkradio.com', '728-159-0385', '1');
insert into "order" (username, email, phone, "statusId") values ('Lyndsay', 'lphilpe@vkontakte.ru', '974-653-8943', '1');
insert into "order" (username, email, phone, "statusId") values ('Carlen', 'clefriecf@smh.com.au', '511-674-5071', '1');
insert into "order" (username, email, phone, "statusId") values ('Elisabeth', 'edesmondg@nsw.gov.au', '850-450-7269', '1');
insert into "order" (username, email, phone, "statusId") values ('Jennifer', 'jtumpaneh@ovh.net', '196-987-7325', '1');
insert into "order" (username, email, phone, "statusId") values ('Agatha', 'aabbyssi@wikipedia.org', '235-600-4244', '1');
insert into "order" (username, email, phone, "statusId") values ('Aurea', 'aegglesonj@simplemachines.org', '265-418-2256', '1');
insert into "order" (username, email, phone, "statusId") values ('Lorettalorna', 'lkochk@chronoengine.com', '293-195-1014', '1');
insert into "order" (username, email, phone, "statusId") values ('Lavinia', 'lwedgwoodl@usa.gov', '914-392-7168', '1');
insert into "order" (username, email, phone, "statusId") values ('Dix', 'dtotarom@ask.com', '656-736-6964', '1');
insert into "order" (username, email, phone, "statusId") values ('Malva', 'mrochewelln@acquirethisname.com', '915-791-5668', '1');
insert into "order" (username, email, phone, "statusId") values ('Drucy', 'doheneryo@scientificamerican.com', '498-850-6019', '1');
insert into "order" (username, email, phone, "statusId") values ('Kris', 'kpfeiferp@businesswire.com', '396-308-7122', '1');
insert into "order" (username, email, phone, "statusId") values ('Cami', 'cswadlingeq@abc.net.au', '977-447-5262', '1');
insert into "order" (username, email, phone, "statusId") values ('Alethea', 'abirkwoodr@xing.com', '254-240-1798', '1');
insert into "order" (username, email, phone, "statusId") values ('Pamela', 'pkeneleysides@gmpg.org', '492-388-4356', '1');
insert into "order" (username, email, phone, "statusId") values ('Tessie', 'tconneaut@answers.com', '674-931-1345', '1');
insert into "order" (username, email, phone, "statusId") values ('Vin', 'vdomoneu@ehow.com', '142-107-1205', '1');
insert into "order" (username, email, phone, "statusId") values ('Vicky', 'vshoryv@yellowbook.com', '486-141-2472', '1');
insert into "order" (username, email, phone, "statusId") values ('Melina', 'meveredw@ebay.com', '256-404-7302', '1');
insert into "order" (username, email, phone, "statusId") values ('Dale', 'dshawx@ebay.com', '741-712-2251', '1');
insert into "order" (username, email, phone, "statusId") values ('Rochell', 'rtandeyy@163.com', '553-687-5738', '1');
insert into "order" (username, email, phone, "statusId") values ('Glynis', 'gwoodlandz@adobe.com', '619-186-0337', '1');
insert into "order" (username, email, phone, "statusId") values ('Moselle', 'mtungate10@yahoo.co.jp', '782-279-6191', '1');
insert into "order" (username, email, phone, "statusId") values ('Brandi', 'bionnidis11@meetup.com', '395-385-9952', '1');
insert into "order" (username, email, phone, "statusId") values ('Alisha', 'aspragg12@weebly.com', '571-512-6635', '1');
insert into "order" (username, email, phone, "statusId") values ('Olimpia', 'obraitling13@hexun.com', '901-670-3815', '1');
insert into "order" (username, email, phone, "statusId") values ('Flor', 'faymeric14@house.gov', '363-775-5760', '1');
insert into "order" (username, email, phone, "statusId") values ('Sidoney', 'sdufty15@ask.com', '172-956-0464', '1');
insert into "order" (username, email, phone, "statusId") values ('Dacie', 'dpuckey16@elpais.com', '251-967-2077', '1');
insert into "order" (username, email, phone, "statusId") values ('Amalia', 'awhitman17@wordpress.org', '530-662-9886', '1');
insert into "order" (username, email, phone, "statusId") values ('Clemmie', 'cfoskin18@cisco.com', '873-703-0298', '1');
insert into "order" (username, email, phone, "statusId") values ('Genvieve', 'gshepstone19@meetup.com', '622-643-3980', '1');
insert into "order" (username, email, phone, "statusId") values ('Drucill', 'dofallowne1a@goo.gl', '874-285-6347', '1');
insert into "order" (username, email, phone, "statusId") values ('Valeria', 'vcassely1b@jugem.jp', '117-440-6818', '1');
insert into "order" (username, email, phone, "statusId") values ('Cairistiona', 'cbillington1c@earthlink.net', '242-531-9207', '1');
insert into "order" (username, email, phone, "statusId") values ('Ardine', 'astrafen1d@wix.com', '161-157-8166', '1');
insert into "order" (username, email, phone, "statusId") values ('Scarlet', 'seasum1e@addthis.com', '187-362-5738', '1');
insert into "order" (username, email, phone, "statusId") values ('Aggi', 'agerrens1f@oakley.com', '642-459-3118', '1');
insert into "order" (username, email, phone, "statusId") values ('Candi', 'cgrieves1g@dyndns.org', '501-648-5800', '1');
insert into "order" (username, email, phone, "statusId") values ('Briny', 'btunuy1h@netlog.com', '779-314-8410', '1');
insert into "order" (username, email, phone, "statusId") values ('Ninnetta', 'nwoolforde1i@amazonaws.com', '934-455-0348', '1');
insert into "order" (username, email, phone, "statusId") values ('Audre', 'astiller1j@reverbnation.com', '402-860-9112', '1');
insert into "order" (username, email, phone, "statusId") values ('Karlyn', 'kbrashaw1k@ted.com', '997-999-9848', '1');
insert into "order" (username, email, phone, "statusId") values ('Giulia', 'gbabbe1l@moonfruit.com', '256-375-2770', '1');
insert into "order" (username, email, phone, "statusId") values ('Crystal', 'chove1m@geocities.jp', '464-993-9856', '1');
insert into "order" (username, email, phone, "statusId") values ('Annabela', 'akinkade1n@state.tx.us', '933-776-1859', '1');
insert into "order" (username, email, phone, "statusId") values ('Rosana', 'rholdworth1o@sfgate.com', '879-974-8597', '1');
insert into "order" (username, email, phone, "statusId") values ('Flori', 'fhamberston1p@cbslocal.com', '933-624-5289', '1');
insert into "order" (username, email, phone, "statusId") values ('Erminia', 'ebaudinet1q@bbc.co.uk', '337-980-9676', '1');
insert into "order" (username, email, phone, "statusId") values ('Lindi', 'lgrummitt1r@walmart.com', '200-868-2740', '1');
insert into "order" (username, email, phone, "statusId") values ('Brena', 'bsiggee1s@wix.com', '577-993-8927', '1');
insert into "order" (username, email, phone, "statusId") values ('Rois', 'rallsebrook1t@cargocollective.com', '606-632-3117', '1');
insert into "order" (username, email, phone, "statusId") values ('Maryellen', 'mcampagne1u@skype.com', '466-639-9716', '1');
insert into "order" (username, email, phone, "statusId") values ('Maureene', 'mbrownbill1v@java.com', '818-911-6801', '1');
insert into "order" (username, email, phone, "statusId") values ('Yvette', 'yspringer1w@unc.edu', '755-268-5485', '1');
insert into "order" (username, email, phone, "statusId") values ('Stacey', 'sdepero1x@eepurl.com', '825-594-4305', '1');
insert into "order" (username, email, phone, "statusId") values ('Alberta', 'ajancy1y@weather.com', '229-327-6634', '1');
insert into "order" (username, email, phone, "statusId") values ('Buffy', 'bkaret1z@myspace.com', '797-533-8449', '1');
insert into "order" (username, email, phone, "statusId") values ('Amalita', 'aspadoni20@google.com.br', '313-974-8851', '1');
insert into "order" (username, email, phone, "statusId") values ('Page', 'pwaltering21@ibm.com', '453-817-9942', '1');
insert into "order" (username, email, phone, "statusId") values ('Allianora', 'afann22@google.com', '325-850-2808', '1');
insert into "order" (username, email, phone, "statusId") values ('Ondrea', 'ovanetti23@miibeian.gov.cn', '976-658-3022', '1');
insert into "order" (username, email, phone, "statusId") values ('Norah', 'nclemett24@goodreads.com', '843-114-0478', '1');
insert into "order" (username, email, phone, "statusId") values ('Imojean', 'ieades25@cocolog-nifty.com', '912-839-2605', '1');
insert into "order" (username, email, phone, "statusId") values ('Georgiana', 'gharrap26@ezinearticles.com', '998-323-0345', '1');
insert into "order" (username, email, phone, "statusId") values ('Elyn', 'eginnally27@adobe.com', '862-890-8927', '1');
insert into "order" (username, email, phone, "statusId") values ('Fedora', 'fhansom28@moonfruit.com', '762-877-4480', '1');
insert into "order" (username, email, phone, "statusId") values ('Carmelle', 'csussans29@a8.net', '501-977-1594', '1');
insert into "order" (username, email, phone, "statusId") values ('Bette-ann', 'btilt2a@blinklist.com', '999-948-0179', '1');
insert into "order" (username, email, phone, "statusId") values ('Daniella', 'dlocks2b@indiegogo.com', '919-832-1070', '1');
insert into "order" (username, email, phone, "statusId") values ('Jenilee', 'jbengall2c@unc.edu', '160-281-6253', '1');
insert into "order" (username, email, phone, "statusId") values ('Jess', 'jpaumier2d@washington.edu', '379-926-3956', '1');
insert into "order" (username, email, phone, "statusId") values ('Jacynth', 'jpovah2e@barnesandnoble.com', '494-223-1358', '1');
insert into "order" (username, email, phone, "statusId") values ('Bobbe', 'bdymott2f@upenn.edu', '828-925-8753', '1');
insert into "order" (username, email, phone, "statusId") values ('Babbie', 'bkynastone2g@pinterest.com', '799-917-3036', '1');
insert into "order" (username, email, phone, "statusId") values ('Margalit', 'mwilfinger2h@ucsd.edu', '257-296-1465', '1');
insert into "order" (username, email, phone, "statusId") values ('Garnet', 'gdolphin2i@bluehost.com', '835-280-9454', '1');
insert into "order" (username, email, phone, "statusId") values ('Dona', 'dbavester2j@creativecommons.org', '124-826-1034', '1');
insert into "order" (username, email, phone, "statusId") values ('Gabrielle', 'gsickert2k@harvard.edu', '464-465-4389', '1');
insert into "order" (username, email, phone, "statusId") values ('Korella', 'ksooley2l@examiner.com', '737-672-5649', '1');
insert into "order" (username, email, phone, "statusId") values ('Shana', 'sashall2m@bbc.co.uk', '193-658-5218', '1');
insert into "order" (username, email, phone, "statusId") values ('Nan', 'nklimpt2n@wired.com', '407-821-2977', '1');
insert into "order" (username, email, phone, "statusId") values ('Rhody', 'rnutley2o@slate.com', '952-759-8172', '1');
insert into "order" (username, email, phone, "statusId") values ('Bonni', 'btrobridge2p@seesaa.net', '670-797-4330', '1');
insert into "order" (username, email, phone, "statusId") values ('Florida', 'fnieass2q@netlog.com', '359-171-3771', '1');
insert into "order" (username, email, phone, "statusId") values ('Susie', 'srigge2r@icio.us', '513-288-9943', '1');

        `)
   }

   public async down(queryRunner: QueryRunner): Promise<void> {}
}
